latteart-org/latteart

README.md
README_ja.md
docs/contributing.md
docs/contributing_ja.md

Add documents for contribution

---

README.md

Add link to doc for contribution

---

README_ja.md
docs/startup/pc.md

add usage for mac

---

launch/src/main.ts

fix #23 change port at startup

---

src/gui/lib/common/util.ts

fix #25 session time display

---

src/gui/vue/pages/operationHistory/organisms/ElementCoverage.vue

fix #8 fix coverage view error

---

src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #27 display full text of notice

---

docs/startup/ios.md
docs/startup/pc.md
launch/capture.command
launch/launch.config.json
launch/manage.command
launch/package.json
launch/src/main.ts
launch/src/server.ts
package.json

fix #30 add startup scripts for mac

---

src/gui/lib/testManagement/TestManagementData.ts
src/gui/lib/testManagement/types.ts
tests/unit/gui/lib/testManagement/Story.spec.ts

fix #70 modify testResultFiles

---

src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #71 modify openCaptureTool method

---

src/gui/vue/pages/captureControl/expCapture/ExpCapture.vue
src/gui/vue/pages/testManagement/ManageView.vue

fix #72 modify download message

---

src/gui/vue/pages/captureControl/expCapture/ExpCapture.vue

fix #73 modify import message

---

src/gui/vue/pages/testManagement/manageEditView/ManageEditView.vue
src/gui/vue/pages/testManagement/manageProgressView/ManageProgressView.vue
src/gui/vue/pages/testManagement/manageQualityView/ManageQualityView.vue
src/gui/vue/pages/testManagement/manageShowView/ManageShowView.vue
src/gui/vue/pages/testManagement/storyView/StoryView.vue
tests/unit/gui/vue/testManagementViewer/ManageProgressView.spec.ts
tests/unit/gui/vue/testManagementViewer/ManageQuality.spec.ts

fix #76 fix update the data on the story screen.

---

src/gui/lib/testManagement/TestManagementData.ts
src/gui/lib/testManagement/types.ts
src/gui/vue/pages/testManagement/ManageView.vue
src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #74 modify option menu

---

src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/pageObject/JSPageObjectCodeGenerator.ts
src/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/pageObject/JSRadioButtonAccessorCodeGenerator.ts
src/gui/lib/operationHistory/scriptGenerator/model/pageObject/method/operation/FormalArgumentsCollector.ts
src/gui/lib/operationHistory/scriptGenerator/model/testSuite/InputGroupCollector.ts
tests/unit/gui/lib/operationHistory/scriptGenerator/codeGenerator/js/pageObject/JSRadioButtonAccessorCodeGenerator.spec.ts
tests/unit/gui/lib/operationHistory/scriptGenerator/model/pageObject/method/operation/FormalArgumentsCollector.spec.ts
tests/unit/gui/lib/operationHistory/scriptGenerator/model/testSuite/InputGroupCollector.spec.ts

fix #83 Normalize radio button name.

---

src/gui/store/testManagement/actions.ts
src/gui/vue/pages/testManagement/manageProgressView/ManageProgressView.vue
src/gui/vue/pages/testManagement/manageShowView/ManageShowView.vue

fix #90 Fix error on  the initial load.

---

src/gui/lib/common/Timestamp.ts
src/gui/lib/common/util.ts
src/gui/lib/eventDispatcher/ClientSideCaptureServiceDispatcher.ts
src/gui/lib/eventDispatcher/RepositoryServiceDispatcher.ts
src/gui/lib/testManagement/StoryDataConverter.ts
src/gui/store/captureControl/actions.ts
src/gui/store/operationHistory/actions.ts
src/gui/vue/pages/captureControl/expCapture/ExpCapture.vue

fix #75 calculate testingtime

---

src/gui/vue/pages/captureControl/expCapture/ExpCapture.vue

fix #98 url empty testresult

---

src/gui/lib/eventDispatcher/RepositoryServiceDispatcher.ts

fix #99 fix test result import error.

---

src/gui/store/operationHistory/actions.ts

fix #105 fix resume error on remote repository.

---

src/gui/vue/pages/captureControl/expCapture/ExpCapture.vue
src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #109 bind remote session to local

---

package.json
yarn.lock

Fix node-ipc version for security

---

src/gui/lib/common/Constants.ts
src/gui/lib/common/enum/SettingsEnum.ts
src/gui/vue/pages/captureControl/configView/ConfigView.vue

fix #46 edge compatible

---

package.json
yarn.lock

fix package error

---

src/gui/vue/pages/captureControl/configView/ConfigView.vue

fix #288 browser setting

---

src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #227 memo text area

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/operationHistory/organisms/OperationList.vue

fix #280 add note filter

---

src/gui/lib/eventDispatcher/RepositoryContainer.ts
src/gui/lib/eventDispatcher/repositoryService/ScreenshotRepository.ts
src/gui/lib/eventDispatcher/repositoryService/ScreenshotsRepository.ts
src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/store/operationHistory/actions.ts
src/gui/vue/molecules/ScrollableDialog.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/CaptureToolHeader.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/GenerateTestScriptButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/MenuButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/ReplayHistoryButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/TestResultFileExportButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/TestResultFileImportButton.vue
src/gui/vue/pages/common/ScriptGenerationOptionDialog.vue
src/gui/vue/pages/common/TestResultImportDialog.vue
src/gui/vue/pages/operationHistory/organisms/HistoryDisplay.vue
src/gui/vue/pages/operationHistory/organisms/ScreenshotsDownloadButton.vue
src/gui/vue/pages/testManagement/ReviewView.vue

fix #21 add screenshots download

---

src/gui/lib/testManagement/History.ts
src/gui/lib/testManagement/StoryDataConverter.ts
src/gui/lib/testManagement/TestManagementData.ts
src/gui/lib/testManagement/types.ts
src/gui/store/testManagement/actions.ts
src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue
tests/unit/gui/vue/testManagementViewer/History.spec.ts

fix #277 bug image view

---

src/gui/lib/testManagement/types.ts
src/gui/vue/molecules/LabelWithTooltip.vue
src/gui/vue/pages/testManagement/manageEditView/organisms/GroupEditor.vue
src/gui/vue/pages/testManagement/manageEditView/organisms/TestMatrixDialog.vue
src/gui/vue/pages/testManagement/manageShowView/organisms/GroupViewer.vue
tests/unit/gui/lib/testManagement/GroupEditInfo.spec.ts
tests/unit/gui/lib/testManagement/actions/UpdateTestMatrixAction.spec.ts

fix #260 add description to viewpoint

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/testManagement/manageEditView/organisms/TestMatrixDialog.vue

fix #260 add placeholder to textarea

---

src/gui/lib/testManagement/StoryDataConverter.ts
src/gui/lib/testManagement/TestManagementData.ts
src/gui/lib/testManagement/types.ts
src/gui/store/testManagement/actions.ts
src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #277 add note image dialog

---

src/gui/lib/testManagement/actions/UpdateTestMatrixAction.ts
src/gui/lib/testManagement/types.ts
src/gui/store/testManagement/actions.ts
src/gui/vue/molecules/UpDownArrows.vue
src/gui/vue/pages/testManagement/manageEditView/organisms/TestMatrixDialog.vue
tests/unit/gui/lib/testManagement/GroupEditInfo.spec.ts
tests/unit/gui/lib/testManagement/actions/UpdateTestMatrixAction.spec.ts

fix #261 change order of viewpoints

---

src/gui/lib/operationHistory/actions/GenerateTestScriptsAction.ts
tests/unit/gui/lib/operationHistory/actions/GenerateTestScriptsAction.spec.ts

fix #333 fix test script generation error message

---

src/gui/lib/captureControl/Reply.ts
src/gui/lib/eventDispatcher/repositoryService/CompressedImageRepository.ts
src/gui/lib/eventDispatcher/repositoryService/ImportProjectRepository.ts
src/gui/lib/eventDispatcher/repositoryService/ImportTestResultRepository.ts
src/gui/lib/eventDispatcher/repositoryService/NoteRepository.ts
src/gui/lib/eventDispatcher/repositoryService/ProjectRepository.ts
src/gui/lib/eventDispatcher/repositoryService/ScreenshotRepository.ts
src/gui/lib/eventDispatcher/repositoryService/SessionRepository.ts
src/gui/lib/eventDispatcher/repositoryService/SettingRepository.ts
src/gui/lib/eventDispatcher/repositoryService/SnapshotRepository.ts
src/gui/lib/eventDispatcher/repositoryService/TestResultRepository.ts
src/gui/lib/eventDispatcher/repositoryService/TestScriptRepository.ts
src/gui/lib/eventDispatcher/repositoryService/TestStepRepository.ts
tests/unit/gui/lib/captureControl/Reply.spec.ts

fix #331 catch invalid server error

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/common/TestResultImportDialog.vue

fix #328 #314 modify testresult import dialog view

---

src/gui/vue/pages/testManagement/storyView/StoryView.vue
src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #322 modify story readonly view

---

src/gui/vue/pages/operationHistory/organisms/OperationList.vue

fix #315 modify search checkbox label

---

src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/DeleteTestResultButton.vue

fix #313 delete empty test result

---

src/gui/vue/pages/testManagement/manageEditView/organisms/TestMatrixDialog.vue

fix #321 disable the down arrow

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json

fix #325 modify replay message

---

src/gui/locale/message_en.json

fix #324 modify menu en message

---

src/gui/vue/pages/testManagement/ReviewView.vue

fix #327 disabled config button when connecting remote

---

src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/RecordButton.vue

fix #330 disable the capture start button in certain situations

---

src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/DeleteTestResultButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/GenerateTestScriptButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/TestResultFileExportButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/TestResultFileImportButton.vue

fix #318 add progress bar messages

---

src/gui/vue/pages/testManagement/ManageView.vue
src/gui/vue/pages/testManagement/manageShowView/ManageShowView.vue

fix #347 disabled progress and quality button when connecting remote

---

src/gui/lib/common/Timestamp.ts
tests/unit/gui/lib/Timestamp.spec.ts

fix #362 fix day difference calculation

---

src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #306 delete testitem

---

src/gui/vue/pages/testManagement/storyView/organisms/SessionInfo.vue

fix #306 modify memo view

---

src/gui/store/testManagement/actions.ts

fix group addition

---

src/gui/store/testManagement/actions.ts

fix #374 modify mutation argument

---

src/gui/store/operationHistory/actions.ts

modify writeSettings

---

src/gui/lib/eventDispatcher/repositoryService/TestScriptRepository.ts
src/gui/lib/operationHistory/actions/GenerateTestScriptsAction.ts
tests/unit/gui/lib/operationHistory/actions/GenerateTestScriptsAction.spec.ts

fix #361 modify script generation api option

---

src/gui/lib/eventDispatcher/RepositoryContainer.ts
src/gui/lib/eventDispatcher/repositoryService/SessionRepository.ts
src/gui/lib/eventDispatcher/repositoryService/StoryRepository.ts
src/gui/lib/testManagement/TestManagementData.ts
src/gui/lib/testManagement/actions/AddNewSessionAction.ts
src/gui/lib/testManagement/actions/DeleteSessionAction.ts
src/gui/lib/testManagement/actions/UpdateStoryAction.ts
src/gui/lib/testManagement/types.ts
src/gui/store/testManagement/actions.ts
src/gui/store/testManagement/getters.ts
src/gui/store/testManagement/mutations.ts
tests/unit/gui/lib/testManagement/Story.spec.ts
tests/unit/gui/lib/testManagement/actions/AddNewSessionAction.spec.ts
tests/unit/gui/lib/testManagement/actions/DeleteSessionAction.spec.ts
tests/unit/gui/lib/testManagement/actions/WriteDataFileAction.spec.ts
tests/unit/gui/vue/testManagementViewer/History.spec.ts

divide project api

---

src/gui/lib/eventDispatcher/repositoryService/LocalStorageSettingRepository.ts
src/gui/store/index.ts
src/gui/vue/pages/testManagement/manageEditView/ManageEditView.vue
src/gui/vue/pages/testManagement/manageEditView/organisms/TestMatrixEditor.vue
src/gui/vue/pages/testManagement/manageShowView/ManageShowView.vue
src/gui/vue/pages/testManagement/manageShowView/organisms/TestMatrixViewer.vue
src/gui/vue/pages/testManagement/storyView/StoryView.vue

modify localstorage

---

src/gui/lib/eventDispatcher/ClientSideCaptureServiceDispatcher.ts
src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/store/captureControl/actions.ts
src/gui/store/captureControl/index.ts
src/gui/store/captureControl/mutations.ts
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/ReplayHistoryButton.vue
src/gui/vue/pages/captureControl/historyView/OperationContextMenu.vue

change run operation interface

---

src/gui/store/captureControl/actions.ts

fix #276 add select operation during replay

---

src/gui/entry/historyViewer/App.vue
src/gui/lib/operationHistory/actions/RegisterOperationAction.ts
src/gui/lib/operationHistory/actions/ResumeAction.ts
src/gui/lib/operationHistory/types.ts
src/gui/store/operationHistory/actions.ts
src/gui/store/operationHistory/index.ts
src/gui/store/operationHistory/mutations.ts
tests/unit/gui/lib/operationHistory/ScreenHistory.spec.ts
tests/unit/gui/lib/operationHistory/actions/ResumeAction.spec.ts

fix #390 remove inputElementInfos

---

src/gui/lib/operationHistory/InputValueTable.ts
src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/store/operationHistory/actions.ts
src/gui/store/operationHistory/index.ts
src/gui/store/operationHistory/mutations.ts
src/gui/vue/pages/common/AutofillRegisterDialog.vue
src/gui/vue/pages/operationHistory/organisms/DecisionTable.vue

#387 autofill register from desision table

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/store/operationHistory/actions.ts
src/gui/store/operationHistory/index.ts
src/gui/store/operationHistory/mutations.ts
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolFooter/AutofillButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolFooter/CaptureToolFooter.vue
src/gui/vue/pages/common/AutofillSelectDialog.vue

add autofill button

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json

#387 modify autofill messages

---

src/gui/store/operationHistory/actions.ts

fix #414 modify autofill title default text

---

src/gui/lib/common/settings/Settings.ts
src/gui/lib/common/settings/SettingsProvider.ts
src/gui/lib/eventDispatcher/repositoryService/LocalStorageSettingRepository.ts
src/gui/lib/eventDispatcher/repositoryService/SettingRepository.ts
src/gui/lib/operationHistory/Coverage.ts
src/gui/lib/operationHistory/actions/setting/ReadSettingAction.ts
src/gui/lib/operationHistory/actions/setting/SaveAutoPopupSettingAction.ts
src/gui/lib/operationHistory/actions/setting/SaveSettingAction.ts
src/gui/lib/operationHistory/types.ts
src/gui/store/operationHistory/actions.ts
src/gui/store/operationHistory/index.ts
tests/unit/gui/store/captureControl/getters.spec.ts

fix #421 modify autofill settings

---

src/gui/lib/operationHistory/actions/AutofillTestAction.ts
src/gui/store/captureControl/actions.ts

fix #418 fix settings to enable autofill

---

src/gui/store/testManagement/actions.ts

fix #425, fix #426 modify updateSession

---

src/gui/store/testManagement/actions.ts

fix #430 modify update testingTime

---

src/gui/vue/molecules/ScrollableDialog.vue
src/gui/vue/molecules/SelectableDataTable.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/CaptureToolHeader.vue
src/gui/vue/pages/operationHistory/organisms/OperationList.vue

fix #295 stop keydown event

---

src/gui/store/testManagement/actions.ts

fix #428, fix #429 modify updateSession

---

src/gui/vue/pages/common/AutofillRegisterDialog.vue
src/gui/vue/pages/common/AutofillSelectDialog.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/AutoFillInputValueContainer.vue

fix #440, fix #441 change operator 'regex' to 'contains'

---

launch/package.json
launch/yarn.lock
package.json
src/gui/lib/operationHistory/graphConverter/SequenceDiagramGraphConverter.ts
src/gui/vue/pages/operationHistory/organisms/MermaidGraphRenderer.vue
tests/unit/gui/lib/operationHistory/graphConverter/SequenceDiagramGraphConverter.spec.ts
yarn.lock

fix #461 upgrade dependencies

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/captureControl/configView/ConfigView.vue
src/gui/vue/pages/common/AutoOperationSelectDialog.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/AutoOperationContainer.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/AutoOperationSetting.vue

fix #407 add auto operation settings

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/common/AutoOperationDialog.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/AutoOperationContainer.vue

fix #477 add operation set details dialog

---

src/gui/store/operationHistory/actions.ts
src/gui/store/operationHistory/index.ts
src/gui/store/operationHistory/mutations.ts
src/gui/vue/molecules/SelectableDataTable.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolFooter/AutoOperationButton.vue
src/gui/vue/pages/common/AutoOperationRegisterDialog.vue
src/gui/vue/pages/operationHistory/organisms/OperationList.vue

fix #475 add "select all" checkbox to operation list

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/molecules/SelectableDataTable.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolFooter/CaptureToolFooter.vue
src/gui/vue/pages/captureControl/historyView/OperationContextMenu.vue
src/gui/vue/pages/common/AutoOperationRegisterDialog.vue
src/gui/vue/pages/operationHistory/organisms/AutoOperationRegisterButton.vue
src/gui/vue/pages/operationHistory/organisms/OperationList.vue
src/gui/vue/pages/operationHistory/organisms/ReplayButton.vue
src/gui/vue/pages/operationHistory/organisms/ReplayOperationsButton.vue

fix #474 fix operations selection

---

src/gui/vue/molecules/SelectableDataTable.vue

fix #475 fix select all

---

src/gui/store/operationHistory/actions.ts
src/gui/vue/pages/operationHistory/organisms/HistoryDisplay.vue
src/gui/vue/pages/operationHistory/organisms/OperationList.vue

fix #484 change operation list order

---

.github/workflows/ci.yml
.github/workflows/manual.yml

fix ci settings

---

src/gui/vue/molecules/SelectableDataTable.vue

fix #474 fix multiple operations selection

---

src/gui/vue/pages/operationHistory/organisms/OperationList.vue

fix #488 remove replay operations button

---

src/gui/lib/common/util.ts
src/gui/lib/eventDispatcher/repositoryService/SettingRepository.ts
src/gui/lib/operationHistory/actions/ExportConfigAction.ts
src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/store/operationHistory/actions.ts
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolHeader/MenuButton.vue
src/gui/vue/pages/common/ConfigExportButton.vue
src/gui/vue/pages/common/ConfigImportButton.vue
src/gui/vue/pages/common/ConfigImportDialog.vue
src/gui/vue/pages/common/DownloadLinkDialog.vue
src/gui/vue/pages/testManagement/ManageView.vue

fix #464 add config import and export.

---

src/gui/lib/eventDispatcher/repositoryService/SettingRepository.ts
src/gui/lib/operationHistory/actions/ExportConfigAction.ts
src/gui/vue/pages/common/ConfigImportButton.vue
src/gui/vue/pages/common/ConfigImportDialog.vue
src/gui/vue/pages/testManagement/ManageView.vue

fix #464 prevent dialog from opening on cancel

---

src/gui/store/captureControl/actions.ts

fix #496 change waiting time after auto operations

---

src/gui/vue/pages/operationHistory/organisms/configViewer/AutoOperationContainer.vue

fix #504 fix layout of auto operation config

---

src/gui/vue/molecules/SelectableDataTable.vue
src/gui/vue/pages/operationHistory/organisms/OperationList.vue

fix #503 fix snapshot view

---

src/gui/lib/common/util.ts
src/gui/lib/operationHistory/Operation.ts
src/gui/vue/pages/common/AutoOperationDialog.vue

fix #501 fix auto operation dialog view

---

src/gui/vue/pages/common/ConfigExportButton.vue
src/gui/vue/pages/common/DownloadLinkDialog.vue
src/gui/vue/pages/testManagement/ManageView.vue

fix #498 download exported config

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json

fix #508 change settings button message

---

src/gui/vue/pages/captureControl/configView/ConfigView.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/AutoOperationSetting.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/AutofillSetting.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/ConfigViewer.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/CoverageSetting.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/ImageCompressionSetting.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/ScreenDefinitionSetting.vue

fix #489 fix config loading when starting capture from management tool.

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/common/AutoOperationRegisterDialog.vue
src/gui/vue/pages/operationHistory/organisms/AutoOperationRegisterButton.vue

fix #509 add invalid type check

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/common/ConfigImportButton.vue
src/gui/vue/pages/operationHistory/organisms/configViewer/ConfigViewer.vue

fix #497 fix config import message.

---

src/gui/vue/pages/captureControl/expCapture/organisms/captureToolFooter/AutofillButton.vue
src/gui/vue/pages/captureControl/expCapture/organisms/captureToolFooter/RunAutoOperationButton.vue

fix #519 disable auto operation button during auto operation.

---

src/gui/vue/pages/operationHistory/organisms/configViewer/ConfigViewer.vue

fix #507 config display from manage screen.

---

src/gui/vue/pages/captureControl/expCapture/organisms/captureToolFooter/RunAutoOperationButton.vue

fix #512 add button activation condition

---

src/gui/vue/molecules/ExecuteDialog.vue
src/gui/vue/pages/captureControl/expCapture/organisms/WindowSelectorDialog.vue
src/gui/vue/pages/captureControl/testOptionDialog/TestOptionDialog.vue
src/gui/vue/pages/common/AutoOperationRegisterDialog.vue
src/gui/vue/pages/common/AutoOperationSelectDialog.vue
src/gui/vue/pages/common/AutofillRegisterDialog.vue
src/gui/vue/pages/common/AutofillSelectDialog.vue
src/gui/vue/pages/common/BugEditDialog.vue
src/gui/vue/pages/common/ConfigImportDialog.vue
src/gui/vue/pages/common/ConfirmDialog.vue
src/gui/vue/pages/common/ExportOptionDialog.vue
src/gui/vue/pages/common/ImportOptionDialog.vue
src/gui/vue/pages/common/NoteEditDialog.vue
src/gui/vue/pages/common/NoticeEditDialog.vue
src/gui/vue/pages/common/ScriptGenerationOptionDialog.vue
src/gui/vue/pages/common/TestPurposeEditDialog.vue
src/gui/vue/pages/common/TestResultImportDialog.vue
src/gui/vue/pages/testManagement/ReviewView.vue
src/gui/vue/pages/testManagement/manageEditView/ManageEditView.vue
src/gui/vue/pages/testManagement/manageEditView/organisms/TestMatrixDialog.vue

fix #518 prevent repeated accept button clicks

---

src/gui/entry/historyViewer/App.vue

fix #396 fix config loading on snapshot.

---

src/gui/lib/testManagement/History.ts
src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/vue/pages/testManagement/ExpManager.vue
src/gui/vue/pages/testManagement/ReviewView.vue
tests/unit/gui/vue/testManagementViewer/History.spec.ts

fix #118 add note context menu to sequence diagram on review view

---

src/common/gateway/repository/testResultRepository.ts
src/gui/components/pages/captureControl/expCapture/organisms/captureToolHeader/DeleteTestResultButton.vue
src/gui/lib/operationHistory/actions/testResult/GetSessionIdsAction.ts
src/gui/locale/message_en.json
src/gui/locale/message_ja.json
src/gui/store/operationHistory/actions.ts

fix #562 fix delete testresult dialog

---

src/gui/locale/message_en.json
src/gui/locale/message_ja.json

fix #562 modify delete testresult message

---

src/common/service/captureClService/captureClClient.ts
src/gui/components/pages/common/NoticeEditDialog.vue

fix #563 fix take note screenshot

---

docs/contributing_ja.md

fix #462 modify contributing document

---

src/common/gateway/repository/types.ts
src/gui/lib/common/util.ts
src/gui/lib/operationHistory/actions/LoadHistoryAction.ts
src/gui/lib/operationHistory/types.ts
src/gui/lib/testManagement/StoryDataConverter.ts
src/gui/store/operationHistory/actions.ts
src/gui/store/testManagement/actions.ts
tests/unit/gui/lib/operationHistory/actions/LoadHistoryAction.spec.ts

fix #550 refactor testingtime

---

.github/workflows/ci.yml
.github/workflows/manual.yml
src/common/gateway/captureCl/captureClServerAdapter.ts
src/common/service/captureClService/captureClClient.ts

fix #156 modify socket io message

---

src/gui/components/molecules/ThumbnailImage.vue
src/gui/components/pages/common/NoteCommonDialog.vue
src/gui/components/pages/common/TakeNoteWithPurposeDialog.vue

fix #593 add thumbnail image

---

src/common/gateway/repository/testResultRepository.ts
src/common/gateway/repository/testScriptRepository.ts
src/common/gateway/repository/types.ts
src/common/service/repositoryService/testResultAccessor.ts
src/common/service/repositoryService/types.ts
src/common/service/types.ts
src/gui/components/pages/captureControl/expCapture/organisms/captureToolHeader/GenerateTestScriptButton.vue
src/gui/components/pages/captureControl/expCapture/organisms/captureToolHeader/TestResultFileExportButton.vue
src/gui/components/pages/captureControl/historyView/HistoryView.vue
src/gui/components/pages/common/TestPurposeEditDialog.vue
src/gui/components/pages/operationHistory/organisms/HistoryDisplay.vue
src/gui/components/pages/operationHistory/organisms/HistorySummaryDiagram.vue
src/gui/components/pages/operationHistory/organisms/ScreenTransitionDiagram.vue
src/gui/components/pages/testManagement/ReviewView.vue
src/gui/lib/operationHistory/graphConverter/SequenceDiagramGraphConverter.ts
src/gui/store/operationHistory/actions.ts
src/gui/store/operationHistory/getters.ts
src/gui/store/operationHistory/index.ts
src/gui/store/operationHistory/mutations.ts
tests/unit/gui/lib/operationHistory/graphConverter/SequenceDiagramGraphConverter.spec.ts

fix #358 sequence view via api

---

docs/contributing_ja.md

fix #156 add links to api documents

---

launch/launch.config.json
launch/src/main.ts
launch/src/server.ts
launch/src/setting.ts

fix #583 enabled to specify launch browser

---

docs/startup/pc.md

fix #583 add about launch settings to the document

---

src/gui/components/pages/common/NoteCommonDialog.vue
src/gui/components/pages/common/TakeNoteDialog.vue

fix #604 modify note common dialog

---

src/gui/components/pages/operationHistory/organisms/HistoryDisplay.vue

fix #606 operation selection during recording

---

docs/startup/pc.md

fix #609 append launch config manual for mac

---

src/gui/components/pages/testManagement/storyView/StoryView.vue
src/gui/entry/historyViewer/main.ts
src/gui/store/operationHistory/actions.ts
templates/historyViewer/index.html

fix #616 fix snapshot sequence

---

src/gui/components/pages/common/ScriptGenerationOptionDialog.vue

fix #619 add standard button tags to request parameters.

---

packages/latteart-repository/pkg.config.json

fix #625 fix test script docs output

---

packages/latteart-gui/templates/historyViewer/index.html

fix #616 fix sequence view loading

---

packages/latteart-repository/pkg.config.json

fix #625 fix package config

---

latteart.code-workspace

update workspace settings

---

packages/latteart-capture-cl/pkg.config.json

fix #630 fix capture-cl packaging

---

packages/latteart-capture-cl/src/index.ts

fix #634 fix latteart-capture-cl log output directory

---

.github/workflows/deploy_docs.yml
.github/workflows/ut_capture_cl.yml
.github/workflows/ut_client.yml
.github/workflows/ut_gui.yml
.github/workflows/ut_repository.yml
docs/contributing_ja.md
packages/latteart-capture-cl/README_ja.md
packages/latteart-cli/README_ja.md
packages/latteart-client/README_ja.md
packages/latteart-gui/README_ja.md
packages/latteart-launch/README_ja.md
packages/latteart-repository/README_ja.md

update documents due to migration to monorepo

---

packages/latteart-gui/src/components/pages/common/ScriptGenerationOptionDialog.vue

fix #632 fix custom button definition field for test script generation

---

packages/latteart-repository/src/lib/scriptGenerator/IdentifierGenerator.ts
packages/latteart-repository/src/lib/scriptGenerator/model/TestScriptModelGenerator.ts
packages/latteart-repository/src/lib/scriptGenerator/model/pageObject/PageObjectFactory.ts
packages/latteart-repository/tests/unit/lib/scriptGenerator/IdentifierGenerator.spec.ts
packages/latteart-repository/tests/unit/lib/scriptGenerator/model/pageObject/PageObjectFactory.spec.ts

fix #637 merge getters of same element on page object

---

packages/latteart-repository/src/domain/testScriptGeneration/codeGenerator/js/pageObject/JSPageObjectMethodNameGenerator.ts
packages/latteart-repository/tests/unit/domain/testScriptGeneration/codeGenerator/js/pageObject/JSPageObjectMethodNameGenerator.spec.ts
packages/latteart-repository/tests/unit/services/TestScriptsService.spec.ts

workaround for #958

---

packages/latteart-repository/src/domain/testScriptGeneration/codeGenerator/js/pageObject/JSPageObjectMethodNameGenerator.ts
packages/latteart-repository/src/domain/testScriptGeneration/model/pageObject/method/operation/PageObjectElementFactory.ts
packages/latteart-repository/src/domain/testScriptGeneration/model/pageObject/method/operation/UnnecessaryOperationFilter.ts
packages/latteart-repository/src/domain/testScriptGeneration/model/pageObject/method/operation/types.ts
packages/latteart-repository/tests/unit/domain/testScriptGeneration/codeGenerator/js/pageObject/JSPageObjectMethodNameGenerator.spec.ts
packages/latteart-repository/tests/unit/domain/testScriptGeneration/model/pageObject/method/operation/PageObjectElementFactory.spec.ts
packages/latteart-repository/tests/unit/services/TestScriptsService.spec.ts

Signed-off-by: knukio <hiro5051@gmail.com>

fix #958 method naming

---

packages/latteart-gui/src/components/molecules/NumberField.vue
packages/latteart-gui/src/components/pages/common/TestPurposeEditDialog.vue

fix #764 display an error message if TestPurpose has duplicate sequences
